# Generated by Django 3.2.3 on 2021-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=55)),
                ('cusername', models.CharField(max_length=55)),
                ('cpassword1', models.CharField(max_length=55)),
                ('cpassword2', models.CharField(max_length=55)),
                ('cgmail_id', models.EmailField(max_length=100)),
            ],
        ),
    ]
